/*
 * Gastos API REST
 * API REST de cadastro de gastos
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Gasto;
import io.swagger.client.model.ResponseEntity;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GastoApiApi
 */
@Ignore
public class GastoApiApiTest {

    private final GastoApiApi api = new GastoApiApi();

    
    /**
     * Cria um novo gasto
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createUsingPOSTTest() throws ApiException {
        Gasto gasto = null;
        Gasto response = api.createUsingPOST(gasto);

        // TODO: test validations
    }
    
    /**
     * Deleta um gasto existente
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteUsingDELETETest() throws ApiException {
        Long id = null;
        ResponseEntity response = api.deleteUsingDELETE(id);

        // TODO: test validations
    }
    
    /**
     * Retorna lista de gastos
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllUsingGETTest() throws ApiException {
        List<Gasto> response = api.findAllUsingGET();

        // TODO: test validations
    }
    
    /**
     * Retorna gasto específico por ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByIdUsingGETTest() throws ApiException {
        Long id = null;
        Gasto response = api.findByIdUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * Cria um novo gasto ou atualiza um existente
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateUsingPUTTest() throws ApiException {
        Gasto gasto = null;
        Long id = null;
        Gasto response = api.updateUsingPUT(gasto, id);

        // TODO: test validations
    }
    
}
